### PR TITLE
Refactors backend

### PR DESCRIPTION
**Pull request by Gabriel-Prisco**
testa ai

### CODE REVIEW

**Review by phklein — APPROVED** [review]
Hello, hello, baby
You called, I can't hear a thing
I have got no service
In the club, you see, see
Wha-wha-what did you say?
Oh, you're breaking up on me
Sorry, I cannot hear you
I'm kinda busy
K-kinda busy
K-kinda busy
Sorry, I cannot hear you
I'm kinda busy
Just a second
It's my favorite song they're gonna play
And I cannot text you with
A drink in my hand, eh
You shoulda made some plans with me
You knew that I was free
And now you won't stop calling me
I'm kinda busy
Stop callin', stop callin'
I don't wanna think any more
I left my head and heart on the dance floor
Stop callin', stop callin'
I don't wanna talk anymore
I got my head and my heart on the dance floor
Eh, eh, eh, eh, eh, eh, eh, eh, eh, eh
Stop telephonin' me
Eh, eh, eh, eh, eh, eh, eh, eh, eh
I'm busy, eh, eh, eh, eh, eh, eh, eh, eh
Stop telephonin' me
Eh, eh, eh, eh, eh, eh, eh
Call all you want, but there's no one home
And you're not gonna reach my telephone
Out in the club, and I'm sippin' that bub
And you're not gonna reach my telephone
Call all you want, but there's no one home
And you're not gonna reach my telephone
Out in the club, and I'm sippin' that bub
And you're not gonna reach my telephone
Boy, the way you blowin' up my phone
Won't make me leave no faster
Put my coat on faster
Leave my girls no faster
I shoulda left my phone at home
'Cause this is a disaster
Callin' like a collector
Sorry, I cannot answer
Not that I don't like you
I'm just at a party
And I am sick and tired
Of my phone ringin'
Sometimes I feel like
I live in Grand Central Station
Tonight I'm not takin' no calls
'Cause I'll be dancin'
'Cause I'll be dancin'
'Cause I'll be dancin'
Tonight I'm not takin' no calls
'Cause I'll be dancin'
Stop callin', stop callin'
I don't wanna think any more
I left my head and my heart on the dance floor
Stop callin', stop callin'
I don't wanna talk any more
I left my head and my heart on the dance floor
Stop callin', stop callin'
I don't wanna think any more
I left my head and my heart on the dance floor
Stop callin', stop callin'
I don't wanna talk any more
I left my head and my heart on the dance floor
Eh, eh, eh, eh, eh, eh, eh, eh, eh, eh
Stop telephonin' me
Eh, eh, eh, eh, eh, eh, eh, eh, eh
I'm busy, eh, eh, eh, eh, eh, eh, eh
Stop telephonin' me
Eh, eh, eh, eh, eh, eh, eh
Can call all you want but there's no one home
And you're not gonna reach my telephone
'Cause I'm out in the club and I'm sippin' that bub
And you're not gonna reach my telephone
Call all you want but there's no one home
And you're not gonna reach my telephone
'Cause I'm out in the club and I'm sippin' that bub
And you're not gonna reach my telephone
My telephone
M-m-my telephone
'Cause I'm out in the club and I'm sippin' that bub
And you're not gonna reach my telephone
My telephone
M-m-my telephone
'Cause I'm out in the club and I'm sippin' that bub
And you're not gonna reach my telephone
We're sorry the number you have reached is not in service at this time
Please check the number, or try your call again

**Comment by casthegrinni** [comment]
There's a stranger in my bed
There's a pounding in my head
Glitter all over the room
Pink flamingos in the pool
I smell like a minibar
DJ's passed out in the yard
Barbies on the barbecue
This a hickey or a bruise?
Pictures of last night ended up online
I'm screwed, oh, well
It's a blacked out blur, but I'm pretty sure it ruled
Damn
Last Friday night
Yeah, we danced on tabletops
And we took too many shots
Think we kissed, but I forgot
Last Friday night
Yeah, we maxed our credit cards
And got kicked out of the bar
So we hit the boulevard
Last Friday night
We went streaking in the park
Skinny dipping in the dark
Then had a ménage à trois
Last Friday night
Yeah, I think we broke the law
Always say we're gonna stop, whoa
This Friday night, do it all again
But this Friday night, do it all again
Trying to connect the dots
Don't know what to tell my boss
Think the city towed my car
Chandelier is on the floor
Ripped my favorite party dress
Warrant's out for my arrest
Think I need a ginger ale
That was such an epic fail
Pictures of last night ended up online
I'm screwed, oh, well
It's a blacked out blur, but I'm pretty sure it ruled
Damn
Last Friday night
Yeah, we danced on tabletops
And we took too many shots
Think we kissed, but I forgot
Last Friday night
Yeah, we maxed our credit cards
And got kicked out of the bar
So we hit the boulevard
Last Friday night
We went streaking in the park
Skinny dipping in the dark
Then had a ménage à trois
Last Friday night
Yeah, I think we broke the law
Always say we're gonna stop, whoa
This Friday night, do it all again (Do it all again)
This Friday night, do it all again
(Do it all again) This Friday night
Last Friday night
Yeah, we danced on tabletops
And we took too many shots
Think we kissed, but I forgot
Last Friday night
Yeah, we maxed our credit cards
And got kicked out of the bar
So we hit the boulevard
Last Friday night
We went streaking in the park
Skinny dipping in the dark
Then had a ménage à trois
Last Friday night
Yeah, I think we broke the law
Always say we're gonna stop, whoa
But this Friday night, do it all again

**Review by casthegrinni — APPROVED** [review]
There's a stranger in my bed
There's a pounding in my head
Glitter all over the room
Pink flamingos in the pool
I smell like a minibar
DJ's passed out in the yard
Barbies on the barbecue
This a hickey or a bruise?
Pictures of last night ended up online
I'm screwed, oh, well
It's a blacked out blur, but I'm pretty sure it ruled
Damn
Last Friday night
Yeah, we danced on tabletops
And we took too many shots
Think we kissed, but I forgot
Last Friday night
Yeah, we maxed our credit cards
And got kicked out of the bar
So we hit the boulevard
Last Friday night
We went streaking in the park
Skinny dipping in the dark
Then had a ménage à trois
Last Friday night
Yeah, I think we broke the law
Always say we're gonna stop, whoa
This Friday night, do it all again
But this Friday night, do it all again
Trying to connect the dots
Don't know what to tell my boss
Think the city towed my car
Chandelier is on the floor
Ripped my favorite party dress
Warrant's out for my arrest
Think I need a ginger ale
That was such an epic fail
Pictures of last night ended up online
I'm screwed, oh, well
It's a blacked out blur, but I'm pretty sure it ruled
Damn
Last Friday night
Yeah, we danced on tabletops
And we took too many shots
Think we kissed, but I forgot
Last Friday night
Yeah, we maxed our credit cards
And got kicked out of the bar
So we hit the boulevard
Last Friday night
We went streaking in the park
Skinny dipping in the dark
Then had a ménage à trois
Last Friday night
Yeah, I think we broke the law
Always say we're gonna stop, whoa
This Friday night, do it all again (Do it all again)
This Friday night, do it all again
(Do it all again) This Friday night
Last Friday night
Yeah, we danced on tabletops
And we took too many shots
Think we kissed, but I forgot
Last Friday night
Yeah, we maxed our credit cards
And got kicked out of the bar
So we hit the boulevard
Last Friday night
We went streaking in the park
Skinny dipping in the dark
Then had a ménage à trois
Last Friday night
Yeah, I think we broke the law
Always say we're gonna stop, whoa
But this Friday night, do it all again

**Comment by casthegrinni** [comment]
Gênio

**Pull request closed without merging**
